### ISSUE TITLE
Нижний слайдер

### ISSUE THREAD

**Issue by darey5** [paulfcdd/joblisting#1]
http://prntscr.com/ao2uwm

Картинки должны переключаться автоматически через 3 секунды. 
Стрелочки убери

**Comment by darey5** [comment]
+ тексты добавь, без красных лэйбов

**Comment by paulfcdd** [comment]
Сделал

**Comment by darey5** [comment]
- [ ] верхний сладер переключаеться вручную (при клике мишкой). Убери автоматичекскую прокрутку

- [ ] добавить тексты в 2 слайдера
