### ISSUE TITLE
Ширина сайта

### ISSUE THREAD

**Issue by darey5** [paulfcdd/joblisting#10]
Ширину сайта сделай как в **fb** http://prntscr.com/aobxnk или как на их сайте
http://prntscr.com/aoby9e
По бокам должно быть пустое пространство

**Comment by paulfcdd** [comment]
есть

**Comment by darey5** [comment]
> По бокам должно быть пустое пространство

Не сделал.

Должно быть так:
![existing](https://cloud.githubusercontent.com/assets/15342587/14378478/cb1a029c-fd7d-11e5-9a84-0e9c8f8bb256.jpg)
