### ISSUE TITLE
Аватарка

### ISSUE THREAD

**Issue by darey5** [paulfcdd/joblisting#2]
Нет аватарки и текста http://prntscr.com/ao2vzy

**Comment by paulfcdd** [comment]
Добавлено

**Comment by darey5** [comment]
Не вижу http://prntscr.com/aobu0h

**Comment by darey5** [comment]
Должно быть так http://prntscr.com/aobu7v
- [ ] Добавить текст
- [ ] Добавить аватарку

**Comment by paulfcdd** [comment]
так есть же и текст и аватарка

**Comment by darey5** [comment]
Уже есть. Я писал это до обновления.
**Сделай авку 200х200**

**Comment by paulfcdd** [comment]
есть

**Comment by darey5** [comment]
Исправить расположение аватарки, как в макете http://prntscr.com/aplnzt
