### ISSUE TITLE
Sponsored Jobs - тексты

### ISSUE THREAD

**Issue by darey5** [paulfcdd/joblisting#23]
- [x] Текст сделать в высоту картинки

![image](https://cloud.githubusercontent.com/assets/15342587/14497678/46a67bb8-01a0-11e6-8ee1-43353a334b49.png)
____________

- [x] Размер шрифта сделать тоже лесенкой, от большего размера к меньшему. Только 4 строки. Не влазит - убрать

**Comment by paulfcdd** [comment]
done
