### ISSUE TITLE
Линия

### ISSUE THREAD

**Issue by darey5** [paulfcdd/joblisting#25]
- [x] Поставь эту линию - разделитель, вместо той что есть
![image](https://cloud.githubusercontent.com/assets/15342587/14606300/480a7fd4-0585-11e6-8390-4e39eefc04e2.png)

- [x] убери пустое место (http://prntscr.com/atr1a3), что б было как тут
![image](https://cloud.githubusercontent.com/assets/15342587/14606331/69065834-0585-11e6-8491-136c536387ed.png)

- [x] после http://prntscr.com/atr1ff --- тоже нужна линия-разделитель

**Comment by paulfcdd** [comment]
есть

**Comment by paulfcdd** [comment]
отметил пункты что все есть)
